#NAME
spring.application.name=quiz-service

#PORT
server.port=8080

#POSTGRE
spring.datasource.url=jdbc:postgresql://postgres:5432/courserdb
spring.datasource.username=courseruser
spring.datasource.password=courserpassword

#HIBERNATE/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true